### ISSUE TITLE
Add profile and nanodegree models

### ISSUE THREAD

**Issue by RyanCCollins** [udacityalumni/alumni-api#16]
We have talked and decided it would be a good idea to add a profile model, along with a One to Many related model for tracking user's nanodegree enrollments.

**Comment by AbigailMathews** [comment]
Probably a many-to-many relationship for the ND info?

**Comment by RyanCCollins** [comment]
Sure, if you think that's best.  I suppose it will work either way.  Right now, I have a 1 - 1 between user to profile.  I can see the benefit of a M-M, however, so that way we can do analysis of how many Users are in each ND and how many NDs each User is a member of.  One thing to keep in mind here, we have several different roles for users.

The main user at first is going to be David as the site admin.  There will also be authors, which are priveleged to do CRUD operations with articles.  Lastly, there will be regular users who are just members of the site.  I think that in the case of Nanodegree specific data collection, we are most interested in the student / basic user population.

**Comment by ghoshabhi** [comment]
So am I understanding this correctly : The normal users(registered) have the following permissions : 
1. Like/Favourite
2. Comment
3. Bookmark

But only "authors" with special permission have the permissions to the CRUD operations on an article ?

**Comment by RyanCCollins** [comment]
Yeah that is correct @abhi. Well know more soon. I'm working with David on outlining all the little specifics.

**Comment by ghoshabhi** [comment]
Alright!!Thank You @RyanCCollins !
