### ISSUE TITLE
Testing Principles

### ISSUE THREAD

**Issue by mikaelm1** [udacityalumni/alumni-api#21]
@RyanCCollins has assigned me the task of running rspec tests on all PR repos as they come in in order to make sure all the tests are passing. I was wandering how others usually approach testing when working on other projects.  Do you follow TDD practices, not write any tests at all, or somewhere in between?

**Comment by RyanCCollins** [comment]
Boo!! Testing ;)

I think I am somewhere in between.  I see the benefit of testing against regressions, especially in a large project, but I don't see much benefit in full on TDD and find that sometimes it even stifles the creative process. 

With the front end, I like to unit test my components, and all the redux stuff.  For back end, Rspec is a great tool and I tend to unit test models and controllers.  I am interested in learning more about Cucumber for BDD in Rails.

Great idea for this article, thanks @mikaelm1!!

**Comment by ghoshabhi** [comment]
I am fairly new, and haven't used the TDD approach or any kind of Testing approach so far!

**Comment by ghoshabhi** [comment]
Okay.. So I have just learnt the basics of TDD => Will try to incorporate it as much as I can! :)
