### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by RyanCCollins** [udacityalumni/alumni-api#25]
I believe we are going to want to build a commenting system to make the site more interactive.  Will be talking with David about this today.

**Comment by ghoshabhi** [comment]
Do we want yo make one of our own ? Or use Disqus ?

**Comment by swaption2009** [comment]
We should build our own comment engine so users don't need to login to another authentication API. We can use Commontator gem to build this feature: https://github.com/lml/commontator

**Comment by RyanCCollins** [comment]
That sounds great, but let's circle back to this at a later time.  David and I spoke yesterday and I have a much better handle on the MVP, so we will definitely have our work cut out for us this coming week.  Commontator looks awesome and I would love to use it when we get to that point.
