### ISSUE TITLE
Authentication with multiple tokens

### ISSUE THREAD

**Issue by RyanCCollins** [udacityalumni/alumni-api#46]
Do we want to have multiple sign ins?  How do we handle having multiple valid tokens?  Should we send a 401 that logs the user out?

**Comment by chashmeetsingh** [comment]
@RyanCCollins we can make a service which will be able to issue multiple tokens for a user, enabling them to have multiple sessions and logging out from one won't affect others. This can be done by having a different model for issuing tokens. Currently the `auth_token` allows only having a single session at a time, according to the schema.

**Comment by chashmeetsingh** [comment]
@RyanCCollins should be closed?

**Comment by RyanCCollins** [comment]
Yes please!
